# This is a basic workflow to help you get started with Actions

name: Python Iaas with github actions

# Controls when the workflow will run
on:
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    -	name:	Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version:	3.8
						
    - name: Install dependencies
      run: |
        make install

    -	name:	Lint code
      run: |
          make lint

    - name: Run tests
      run: |
          make test

    -	name:	Format code
      run: |
          make format
